package u1a6.math.methods;

/**
 *
 * @author c0d3x
 */
public class GUIcomponents extends javax.swing.JFrame {

    /**
     * Creates new form GUIcomponents
     */
    public GUIcomponents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExitBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        Num1Field = new javax.swing.JTextField();
        Num2Field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SqrtBtn = new javax.swing.JButton();
        MaxMinBtn = new javax.swing.JButton();
        PowerBtn = new javax.swing.JButton();
        AbsBtn = new javax.swing.JButton();
        SubLbl = new javax.swing.JLabel();
        SignLbl2 = new javax.swing.JLabel();
        Signlbl1 = new javax.swing.JLabel();
        OutputField = new javax.swing.JTextField();
        SignLbl3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        Num2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2FieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        jLabel1.setText("Math Methods Program");

        SqrtBtn.setText("Square Root");
        SqrtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtBtnActionPerformed(evt);
            }
        });

        MaxMinBtn.setText("Max/Min");
        MaxMinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxMinBtnActionPerformed(evt);
            }
        });

        PowerBtn.setText("Power");
        PowerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerBtnActionPerformed(evt);
            }
        });

        AbsBtn.setText("Abs Value");
        AbsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbsBtnActionPerformed(evt);
            }
        });

        SubLbl.setText("Please Enter A Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Signlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SignLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SignLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(SubLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addComponent(OutputField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PowerBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AbsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SqrtBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaxMinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(ClearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Num1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Num2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SignLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Signlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SignLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OutputField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxMinBtn)
                    .addComponent(SqrtBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerBtn)
                    .addComponent(ClearBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbsBtn)
                    .addComponent(ExitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0); // Exit the application
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void PowerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerBtnActionPerformed

        double num1 = Double.parseDouble(Num1Field.getText());
        double num2 = Double.parseDouble(Num2Field.getText());
        double result = Math.pow(num1, num2);

        String output = String.format("%.2f raised to the power of %.2f is %.2f", num1, num2, result);
        OutputField.setText(output);
    }//GEN-LAST:event_PowerBtnActionPerformed

    private void SqrtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrtBtnActionPerformed

        double num1 = Double.parseDouble(Num1Field.getText());
        double sqrt1 = Math.sqrt(num1);
        double num2 = Double.parseDouble(Num2Field.getText());
        double sqrt2 = Math.sqrt(num2);

        String output = String.format("The square root of %.2f and %.2f is %.2e and %.2e", num1, num2, sqrt1, sqrt2);
        OutputField.setText(output);


    }//GEN-LAST:event_SqrtBtnActionPerformed

    private void MaxMinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxMinBtnActionPerformed

        int num1 = Integer.parseInt(Num1Field.getText());
        int num2 = Integer.parseInt(Num2Field.getText());

        int max = num1 > num2 ? num1 : num2;
        int min = num1 < num2 ? num1 : num2;

        OutputField.setText("Max value is " + max + " and the min value is " + min);

    }//GEN-LAST:event_MaxMinBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        Num1Field.setText("");
        Num2Field.setText("");
        OutputField.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void AbsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsBtnActionPerformed
        double num1 = Double.parseDouble(Num1Field.getText());
        double num2 = Double.parseDouble(Num2Field.getText());

        double abs1 = Math.abs(num1);
        double abs2 = Math.abs(num2);

        OutputField.setText("The absolute value of " + num1 + " is " + abs1 + " and the absolute value of " + num2 + " is " + abs2);
    }//GEN-LAST:event_AbsBtnActionPerformed

    private void Num2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num2FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIcomponents.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIcomponents().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbsBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton MaxMinBtn;
    private javax.swing.JTextField Num1Field;
    private javax.swing.JTextField Num2Field;
    private javax.swing.JTextField OutputField;
    private javax.swing.JButton PowerBtn;
    private javax.swing.JLabel SignLbl2;
    private javax.swing.JLabel SignLbl3;
    private javax.swing.JLabel Signlbl1;
    private javax.swing.JButton SqrtBtn;
    private javax.swing.JLabel SubLbl;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
